# Generated by Django 4.2 on 2023-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
            ],
        ),
    ]
